version: '3'

services:
  database:
    container_name: Database
    build:
      context: database
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    networks:
      - triply
    volumes:
      - pg-data:/var/lib/postgresql/data

  backend:
    container_name: Backend
    build:
      context: triply
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/{DB_NAME}
    ports:
      - 8080:8080
    networks:
      - triply
    depends_on:
      - database

networks:
  triply:
    driver: bridge

volumes:
  pg-data: