spring:
  application:
    name: backend
    security:
      jwt:
        secret-key: ${JWT_SECRET}
        expiration: ${JWT_EXPIRATION}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

  sql:
    init:
      data-locations: classpath:init.sql
      mode: always

  web:
    resources:
      static-locations: file:data/uploads/,classpath:/static/

  mvc:
    static-path-pattern: /data/uploads/**