CREATE TABLE IF NOT EXISTS roles (
    id SERIAL UNIQUE PRIMARY KEY,
    name VARCHAR(255) UNIQUE
);

INSERT INTO roles(name) VALUES('ROLE_ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO roles(name) VALUES('ROLE_USER') ON CONFLICT DO NOTHING;
